name: Automatic Rebase

on: [pull_request_target]

permissions:
  contents: read

jobs:
  _:
    permissions:
      contents: write  # for ljharb/rebase to push code to rebase
      pull-requests: read  # for ljharb/rebase to get info about PR

    name: "Automatic Rebase"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ljharb/rebase@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
